---
# tasks file for dbserver

- name: update the packages in each server
  package: 
    name: '*'
    state: latest

- name: Install nginx package
  package: 
    name: nginx
    state: latest

- name: Start nginx webserver
  service:
    name: nginx
    state: started

- name: Update nginx confs for WordPress + PHP
  template: "src=../templates/default-site.conf dest=/etc/nginx/sites-available/{{website_name}} owner=www-data group=www-data mode=0644"
  become: yes

- name: Enable site
  file: src=/etc/nginx/sites-available/{{website_name}} dest=/etc/nginx/sites-enabled/{{website_name}} owner=www-data group=www-data state=link
  notify:
    - restart nginx

#- name: Create nginxuser in each server
#  hosts: webservers, dbservers
#  script: add_nginx_user.sh 
